export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'
export const UPDATE_INDEX_SELECTED_QUESTION = 'UPDATE_INDEX_SELECTED_QUESTION'
export const UPDATE_CORRECT_ANSWEARS = 'UPDATE_CORRECT_ANSWEARS'
export const UPDATE_SELECTED_ANSWEAR = 'UPDATE_SELECTED_ANSWEAR'