export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'
export const UPDATE_INDEX_SELECTED_QUESTION = 'UPDATE_INDEX_SELECTED_QUESTION'
export const UPDATE_CORRECT_ANSWERS = 'UPDATE_CORRECT_ANSWERS'
export const UPDATE_SELECTED_ANSWER = 'UPDATE_SELECTED_ANSWER'